### PR TITLE
Allow react 17 as a peer dependency

### PR DESCRIPTION
**Pull request by jlmorales-xumak**

### CODE REVIEW

**Comment by beetlerom** [comment]
@jlmorales-xumak The SPA SDK is not yet compatible with react 17.

**Comment by jlmorales-xumak** [comment]
@beetlerom Thanks for the reply. Is there any estimated time for this update? I'm integrating the SPA SDK in a React 17 app and, I haven't encountered any errors so far but, it would be great to have official support.

**Comment by beetlerom** [comment]
@jlmorales-xumak We have started support tasting react 17 support, I'll return with more updates when I have them.

**Comment by Jontii** [comment]
Any update on this?

**Comment by ssured** [comment]
Can you give a status update on this? React 18 is almost there...

**Comment by beetlerom** [comment]
Hey folks, I know this took a while, but we have just released [15.5.0](https://github.com/bloomreach/spa-sdk/releases/tag/spa-sdk-15.5.0) which includes official support for React 17.

React 18 is on our roadmap, but it's unclear what the adoption rate is a.t.m. Do you mind sharing if you are using it already or you would like to use it in combination with the SDK? Thanks!

**Comment by beetlerom** [comment]
Closed since this is now supported.

**Pull request closed without merging**
